### PR TITLE
Fix build check plugin in a custom project directory

### LINKED ISSUE #607: 'checkBuildEnvironment' not found on a KMM project with Cocoapods
I'm using build checks on a kotlin multiplatform project. At first I was using a regular setup (project generated with the [android studio plugin](https://plugins.jetbrains.com/plugin/14936-kotlin-multiplatform-mobile)), and it worked well. But then I moved my shared project to cocoapods using [this guide](https://kotlinlang.org/docs/reference/native/cocoapods.html), build checks started failing with the following error:
```
* What went wrong:
Task 'checkBuildEnvironment' not found in project ':shared'.
```
I'd created a [sample project](https://github.com/PhilipDukhov/AvitoBuildchecksCocoapods) which shows the error
In case you don't have Xcode, you can just test it with 
```
 ./gradlew -p shared :shared:syncFramework -Pkotlin.native.cocoapods.target=ios_x64 -Pkotlin.native.cocoapods.configuration=Debug -Pkotlin.native.cocoapods.cflags= -Pkotlin.native.cocoapods.paths.headers= '-Pkotlin.native.cocoapods.paths.frameworks= "shared/build/cocoapods/framework"'
```
that's the command run by xcode in order to build the module.

### PR DESCRIPTION
**Pull request by eugene-krivobokov**
Build check plugin adds a task `checkBuildEnvironment` to Gradle start parameters to run check on every build. 

```
./gradlew :module:build

> Task :module:build
> Task :checkBuildEnvironment
```

It didn't work with a custom project directory:

```
./gradlew -p module :module:task
```

In this case, Gradle works inside a module/ directory and can't find the `checkBuildEnvironment` task.

Closes #607

### CODE REVIEW

File: subprojects/gradle/buildchecks/src/main/kotlin/com/avito/android/plugin/build_param_check/BuildParamCheckPlugin.kt [hunk 1]
```diff
@@ -78,10 +79,7 @@ open class BuildParamCheckPlugin : Plugin<Project> {
             it.group = "verification"
             it.description = "Check typical build problems"
         }
-        project.gradle.startParameter.setTaskNames(
-            // getter returns defencive copy
-            project.gradle.startParameter.taskNames + "checkBuildEnvironment"
-        )
+        project.gradle.startParameter.addTaskNames(":checkBuildEnvironment")
```
Comment (eugene-krivobokov) [inline subprojects/gradle/buildchecks/src/main/kotlin/com/avito/android/plugin/build_param_check/BuildParamCheckPlugin.kt:82]: the fix

**Review by dsvoronin — APPROVED** [review]
